pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: "${env.LOG_ROTATOR_NUM_TO_KEEP}", artifactNumToKeepStr: "${env.LOG_ROTATOR_ARTIFACT_NUM_TO_KEEP}"))
        timestamps()
    }

    stages {
        stage('Clean WorkSpace') {
            steps {
               cleanWs()
            }
        }

        stage('DEBUG -> Incoming Parameters') {
            steps {
               println "FROM: " + "$FROM"
               println "TO: " + "$TO"
               println "SUBJECT: " + "$SUBJECT"
               println "BODY: " + "$BODY"
            }
        }   

        stage('Send Email') {
            steps {
               emailext (
                   from: "${FROM}",
                   to: "${TO}",
                   subject: "${SUBJECT}",
                   body: "${BODY}"
               )
            }
        }
    }   
}